---

- name: Install bg info
  win_chocolatey:
    name: bginfo

- name: Set timezone to 'Romance Standard Time' (GMT+01:00)
  win_timezone:
    timezone: Romance Standard Time

- name: Set the region format to Denmark and copy settings to new profiles
  win_region:
    format: da-DK
    copy_settings: yes

- name: Resize the C Drive to it's maximum size 
  win_partition:
    partition_size: -1
    partition_number: 1
    disk_number: 0
