---

- name: Install bg info
  win_chocolatey:
    name: bginfo
  # become: yes
  
- name: Ensure server is join to domain
  win_domain_membership:
    dns_domain_name: bestcorp.net
    domain_admin_user: "{{ domain_admin_user }}"
    domain_admin_password: "{{ domain_admin_password }}"
    domain_ou_path: "{{ domain_ou_path }}"
    state: domain
  register: domain_state

- name: Reboot server if required
  win_reboot:
  when: domain_state.reboot_required