domain_admin_user: "{{ lookup('community.general.hashi_vault', 'ET/data/automated_build/domain_join:username', token=vault_token, url=vault_addr) }}" 
domain_admin_password: "{{ lookup('community.general.hashi_vault', 'ET/data/automated_build/domain_join:password', token=vault_token, url=vault_addr ) }}" 
domain_ou_path: "OU=Azure,OU=Servers,OU=Bestseller Computers,DC=bestcorp,DC=net"
