---

- name: Ensure server is join to domain
  win_domain_membership:
    dns_domain_name: bestcorp.net
    domain_admin_user: "{{ domain_admin_user }}"
    domain_admin_password: "{{ domain_admin_password }}"
    domain_ou_path: "{{ domain_ou_path }}"
    state: domain
  register: domain_state

- name: Reboot server if required
  win_reboot:
  when: domain_state.reboot_required

- name: Install ActiveDirectory Powershell Module
  win_feature:
    name: RSAT-AD-PowerShell
    state: present

- name: Create Domain group BestcorpServerAdmin{{ ansible_hostname }}
  win_domain_group:
    name:  BestcorpServerAdmin{{ ansible_hostname }}
    description: Resource - Gives Admin rights to {{ ansible_hostname }}
    scope: global
    path: "OU=serverAdmin,OU=Resources,OU=Administration,OU=Bestseller Special,DC=bestcorp,DC=net"
    domain_server:  "{{ domain_server }}"
    domain_username: "{{ domain_admin_user }}"
    domain_password: "{{ domain_admin_password }}"

- name: Adds the Domain group BestcorpServerAdmin{{ ansible_hostname }} to local Administrator group
  win_group_membership:
    name: Administrators
    members:
      - BESTCORP\BestcorpServerAdmin{{ ansible_hostname }}

- name: Remove ActiveDirectory Powershell Module
  win_feature:
    name: RSAT-AD-PowerShell
    state: absent